travis:
  secure:
    BINSTAR_TOKEN: SBiXk/C5lFt7S3pub3D9tnz379c0QFcf9ZaTjH7cA1oycdfYtEV9M7feURf9/ssTaFpA2nBsEYv7zOxp9UG+nc+n2QGtWWNWqmUKeVqR3OyE76PyzTLazvDNS8n/D1qCscMeXrycrQPiBIzeQnXFxZHxDkduen00yL2TaFmpwthqad2lJObN5pdXgz8/MnqLwfLyRUcQoP3l994RUsr/o5pRgUScii4TjW/kExJ087h8u78N+tX/8VbSUk6nZccIxKcPsc4fo9lA0GaW70fAv9J6KK0IuHNPzLWNjHq7Xlp6lu5hMIw6xoXqgnj/Chja5EAf1mZrbRgOGH3GIsGdxO6TYgtgTz94PJnPgSeHYiz9+m8QLJinoOpouldG+vLUvWcu4YpOGbFUuy57xYQoiolAAGJEQpe09lzDYxZlLykXoyyrXtphfJaUy16R0NmhGcy1XtT9AtJQnnI3k15VDGNxHtk3N21kZSr5N83avzX/TRKUmZ/vDvZzSPgnDUdWYe0RGC+7bYXnN/E3wlJRs6wTsuaRUojzagj0QFDwExha3pwniGqD+VpCn+BSXWxMd5DEbx9PbxyxZOyyM1qAjWC2PHL1XZiZO1mM+RIJEbPQmFJiy+XaHzFV8yNbvZX9IEN0I0Z23nbt7V0/nB1MiE+A5VP4vc9AAtPlyHg/jAg=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
provider:
  win: azure
